### ISSUE TITLE
Company directory function

### ISSUE THREAD

**Issue by raphael-parker** [segment-boneyard/hermes#26]
I'd love it if we had a company directory with people's cell numbers. Even cooler would be if we could enter:

@hermes cell ian@segment.com and Hermes would return Ian's cell number to me.

@ianstormtaylor @ivolo

**Comment by ianstormtaylor** [comment]
Sounds sweet. It would be cool to get this in the same sort of DB we use for our actual product. We could imagine having an internal app that can use the same data.

cc @travisjeffery just for ideas — I don't think the actual database is a "now" thing, but we could just use YAML or something for it for now

**Comment by travisjeffery** [comment]
a yml file would be enough for now i think. 

this should replace this page https://github.com/segmentio/hq/wiki/List-of-People too. or at least we shouldn't have multiple copies of data in different places. that page is probably going to get unwieldy anyway.

**Comment by travisjeffery** [comment]
also moving this issue over to our hubeau org https://github.com/segmentio/hubeau/issues/122. maybe calling that repo "segment-hermes" or "private-hermes" would be clearer
