### ISSUE TITLE
Org billing function

### ISSUE THREAD

**Issue by raphael-parker** [segment-boneyard/hermes#27]
@ivolo @ianstormtaylor 

When I want to see whether a company is on a paid plan or using a coupon I have to go to the settings/billing page. That seems like the kind of thing that should be available through Hermes. What I'd like to do is enter the org name like this:

@hermes billing [org]

And Hermes will return:
What play they should be on based on usage
What plan they're on
Whether they're over on usage
Whether they have a credit card account on file
What their billing date is
How long they've been paying us

**Comment by travisjeffery** [comment]
@raphael-parker yo raph, make these issues at https://github.com/segmentio/hubeau/issues. this repo is for the public open source version of hermes for people outside of segment.
