### ISSUE TITLE
deploy is broken

### ISSUE THREAD

**Issue by travisjeffery** [segment-boneyard/hermes#9]
each time i do 

`@hermes deploy docs 1.2.0`

i get:

`Deploying docs 1.2.0...`

followed immediately with hermes leaving the room and the docs not being deployed.

**Comment by juliangruber** [comment]
hermes is so passive aggressive...

**Comment by travisjeffery** [comment]
yep

seems like segmentio/hubaeu might be a better fit for this issue, moving this issue over there https://github.com/segmentio/hubeau/issues/45
